### ISSUE TITLE
请问为什么要把图片转成binaries

### ISSUE THREAD

**Issue by buptlj** [littlepure2333/SamplingAug#3]
感谢作者的贡献，论文想法很好！有个疑问，就是数据预处理时，为什么要把png转成binaries，感觉直接opencv读图就行啊，为什么用pickle来回保存、读取。

**Comment by littlepure2333** [comment]
感谢您的关注！我们数据预处理将png先解码好转成binaries是为了之后使用的时候可以更快地读取图片信息，如果每次都用opencv读取的话会增加解码图片的额外时间，不过不太注重这块时间的话其实也没有什么所谓~（此处理参考[EDSR Repo](https://github.com/sanghyun-son/EDSR-PyTorch#how-to-train-edsr-and-mdsr) )
