### ISSUE TITLE
关于patchnet

### ISSUE THREAD

**Issue by qinzizizi** [littlepure2333/SamplingAug#6]
您好红发哥，想询问一下可不可以借鉴一下您对patchnet的复现，看您论文中有与原本用于去马赛克任务的patchnet的复现。

**Comment by littlepure2333** [comment]
您好，NeurIPS之后我找找看看回复你获取Outlook for Android

**Comment by qinzizizi** [comment]
感谢您，谢谢

**Comment by qinzizizi** [comment]
不好意思想再打扰您一下，请问您还记得您在PatchNet中是如何进行二值化的吗

**Comment by qinzizizi** [comment]
不好意思红发哥，想再打扰您一下，不知道您还能找到那段代码吗。麻烦您啦

**Comment by littlepure2333** [comment]
Hi不好意思最近事情比较多，我已经通过邮件回复您了，请查收。
